### ISSUE TITLE
Won’t build pyswisseph on MacOS 13.4

### ISSUE THREAD

**Issue by dalerye** [astrorigin/pyswisseph#63]
Using “pip install pyswisseph” produces a fatal “failed building wheel for pyswisseph” error:

In file included from libswe/swell.c:61:
In file included from libswe/swejpl.h:66:
linswe/sweodef.h:170:10: fatal error: ‘math.h’ file not found
#include <math.h>

The same error recurs in trying to pip install other libraries that depend on pyswisseph, like kerykeion

I am using pip 21.3.2 on Python 3.10.1 on MacOS 13.4 with the Xcode 14.3 tools installed.

**Comment by ShadowJonathan** [comment]
Confirmed the issue: the wheel with the highest Python version is Python 3.9, meaning pip can't find an applicable wheel

**Comment by astrorigin** [comment]
The latest release v2.10.03.2 should fix that problem. Please try again and let us know.

**Comment by dalerye** [comment]
Thanks for the fast response. It builds fine now, I think, but in Python 3.10, I still get an error: " No module named 'pyswisseph' ." I have been involved with computers since 1965, but I cannot seem to master the mysteries of UNIXish PATH variables. I installed Python 3.11, but the shell updater left me still running 3.10.1 when I invoke 'python3' so if pyswisseph is in the libraries for 3.11, my python still isn't seeing it. That is probably on me, not on you.

**Comment by ShadowJonathan** [comment]
pyswisseph is importable via `import swisseph`

**Comment by dalerye** [comment]
pip tells me that pyswisseph is installed. I cannot use it, but that is not your problem. I got everything I paid for ;).
